@host = http://localhost:5000

POST  {{host}}/tourists/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxM2JkZGM3NS1hYzlmLTQ4MTYtYTM3NC0xYzg4MzE4NTA5YTQiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwicm9sZSI6IkN1c3RvbWVyIiwiYWdlbmN5SWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJlbWFpbCI6ImRvZUpvaG5AbXMubmV0IiwiUGVybWlzc2lvbnMiOlsiUmVhZEV4Y3Vyc2lvbnMiLCJSZWFkUGFja2FnZXMiLCJSZWFkQWdlbmNpZXMiLCJSZWFkSG90ZWxzIiwiUmVhZEhvdGVsRGVhbHMiLCJSZWFkUGFja2FnZXMiLCJXcml0ZVRvdXJpc3RzIiwiUmVhZFRvdXJpc3RzIl0sImp0aSI6IjdkNmY3MTc1LWQzYWUtNDRhMC04OGIwLTQ0NmRmMzM2MTAxYSIsImV4cCI6MTcxMjA0MTUwOSwiaXNzIjoiVHJhdmVsQWdlbmN5IiwiYXVkIjoiVHJhdmVsQWdlbmN5In0.rIQ7f8LJZsTy93xXsfF9pNfS_wvA5CRn8iidCxEFl_U

{
  "userId" : "13bddc75-ac9f-4816-a374-1c88318509a4",
  "CI": "02111460409" ,
  "firstName": "Ke",
  "lastName": "Adams",
  "nationality": "Ireland"
}


###

POST  {{host}}/tourists/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzODE2NjEzYS02M2RkLTQ1MWItYjg3ZS02ZDc2MWY2NTcwZTQiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwicm9sZSI6IkN1c3RvbWVyIiwiUGVybWlzc2lvbnMiOlsiUmVhZEV4Y3Vyc2lvbnMiLCJSZWFkUGFja2FnZXMiLCJSZWFkQWdlbmNpZXMiLCJSZWFkSG90ZWxzIiwiUmVhZEhvdGVsRGVhbHMiLCJSZWFkUGFja2FnZXMiLCJXcml0ZVRvdXJpc3RzIl0sImp0aSI6ImZjMTFhNWE1LTNmZGItNGQ5NS04NzMyLWRlODY2ZGM3YjA5MSIsImV4cCI6MTcxMjAxNzgzNSwiaXNzIjoiVHJhdmVsQWdlbmN5IiwiYXVkIjoiVHJhdmVsQWdlbmN5In0.QeZ-HwY-hRgbqtLTZLoi9NlTd6PXP5mHy_bCQ3Cljj8

{
  "id": "1110987654321",
  "firstName": "Rachel",
  "lastName": "Green",
  "nationality": "Canada"
}