@host = http://localhost:5000

POST  {{host}}/tourists/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxM2JkZGM3NS1hYzlmLTQ4MTYtYTM3NC0xYzg4MzE4NTA5YTQiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwicm9sZSI6IkN1c3RvbWVyIiwiYWdlbmN5SWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJlbWFpbCI6ImRvZUpvaG5AbXMubmV0IiwiUGVybWlzc2lvbnMiOlsiUmVhZEV4Y3Vyc2lvbnMiLCJSZWFkUGFja2FnZXMiLCJSZWFkQWdlbmNpZXMiLCJSZWFkSG90ZWxzIiwiUmVhZEhvdGVsRGVhbHMiLCJSZWFkUGFja2FnZXMiLCJXcml0ZVRvdXJpc3RzIiwiUmVhZFRvdXJpc3RzIl0sImp0aSI6IjdkNmY3MTc1LWQzYWUtNDRhMC04OGIwLTQ0NmRmMzM2MTAxYSIsImV4cCI6MTcxMjA0MTUwOSwiaXNzIjoiVHJhdmVsQWdlbmN5IiwiYXVkIjoiVHJhdmVsQWdlbmN5In0.rIQ7f8LJZsTy93xXsfF9pNfS_wvA5CRn8iidCxEFl_U

{
  "userId" : "13bddc75-ac9f-4816-a374-1c88318509a4",
  "CI": "02111460200" ,
  "firstName": "Ke",
  "lastName": "Adams",
  "nationality": "Ireland"
}


###

POST  {{host}}/tourists/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMmZlNzNiNS01M2Y0LTQ3NzMtOTk3YS00YWQwYmYwYWRjZTEiLCJnaXZlbl9uYW1lIjoiTmF0YXNoYSIsImZhbWlseV9uYW1lIjoiQXRraW5zIiwicm9sZSI6IkN1c3RvbWVyIiwiYWdlbmN5SWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJlbWFpbCI6ImF0a2luc05hdEBtcy5uZXQiLCJQZXJtaXNzaW9ucyI6WyJSZWFkRXhjdXJzaW9ucyIsIlJlYWRQYWNrYWdlcyIsIlJlYWRBZ2VuY2llcyIsIlJlYWRIb3RlbHMiLCJSZWFkSG90ZWxEZWFscyIsIlJlYWRQYWNrYWdlcyIsIldyaXRlVG91cmlzdHMiLCJSZWFkVG91cmlzdHMiXSwianRpIjoiNmExZmU1N2EtMDI2My00ZTBiLWFiZTktZmI3NWMxNWJlZjEzIiwiZXhwIjoxNzEyMDQ2ODkyLCJpc3MiOiJUcmF2ZWxBZ2VuY3kiLCJhdWQiOiJUcmF2ZWxBZ2VuY3kifQ.lPGANoObukv1YhPIPlCRmjjwlN-FHtZAy43VqZQmNXo

{
  "UserId": "cf6c33cd-500e-49d8-9792-fbe5a914560b",
  "CI" : "0100120012",
  "firstName": "Chandler",
  "lastName": "Green",
  "nationality": "Cuba"
}