@host = http://localhost:5000

GET  {{host}}/tourists/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNTdhNmVhNC0wOWIwLTQ5MjAtYmE5MC1jMzc3MmQ5OGUxNzUiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwicm9sZSI6IkN1c3RvbWVyIiwiUGVybWlzc2lvbnMiOlsiUmVhZEV4Y3Vyc2lvbnMiLCJSZWFkUGFja2FnZXMiLCJSZWFkQWdlbmNpZXMiLCJSZWFkSG90ZWxzIiwiUmVhZEhvdGVsRGVhbHMiLCJSZWFkUGFja2FnZXMiLCJXcml0ZVRvdXJpc3RzIiwiUmVhZFRvdXJpc3RzIl0sImp0aSI6IjM0OGY2M2NkLTEzOTktNGQ0Yi04ODAyLWJkZWM5YTEyMjhhMiIsImV4cCI6MTcxMjAxODQwOCwiaXNzIjoiVHJhdmVsQWdlbmN5IiwiYXVkIjoiVHJhdmVsQWdlbmN5In0.zqK9GLDMiFwYAtAglbfIcAavqV4Nw-YT_gz3BWsNthA