@host = http://localhost:5000

POST {{host}}/backOffice/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODk1NTc2Ni0wNzE0LTQ5ZjMtOWE2Yy04ODM2OTkzYjgzMWUiLCJnaXZlbl9uYW1lIjoiU2hlcmxvY2siLCJmYW1pbHlfbmFtZSI6IkhvbG1lcyIsInJvbGUiOiJTdXBlciBBZG1pbiIsImFnZW5jeUlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIiwiZW1haWwiOiJob2xtZXNAbWFpbC5uZXQiLCJQZXJtaXNzaW9ucyI6WyJXcml0ZVVzZXJzIiwiV3JpdGVFeGN1cnNpb25zIiwiV3JpdGVQYWNrYWdlcyIsIldyaXRlUm9sZXMiLCJXcml0ZVRvdXJpc3RzIiwiV3JpdGVGYWNpbGl0aWVzIiwiV3JpdGVQYWNrYWdlUmVzZXJ2YXRpb24iLCJXcml0ZUFnZW5jaWVzIiwiUmVhZEFnZW5jaWVzIiwiUmVhZEhvdGVscyIsIlJlYWRIb3RlbERlYWxzIiwiUmVhZFBhY2thZ2VzIiwiUmVhZEV4Y3Vyc2lvbnMiLCJSZWFkVXNlcnMiLCJSZWFkUm9sZXMiLCJSZWFkQWlybGluZXMiLCJSZWFkVG91cmlzdHMiLCJSZWFkRmFjaWxpdGllcyIsIlJlYWRQYWNrYWdlUmVzZXJ2YXRpb24iLCJSZWFkU3RhdGlzdGljcyJdLCJqdGkiOiJiOGUyYzFhYi1iYmIxLTQ5ODgtYTg0NS1kMjI4MWZkMjgxMTMiLCJleHAiOjE3MTIwNTIwODUsImlzcyI6IlRyYXZlbEFnZW5jeSIsImF1ZCI6IlRyYXZlbEFnZW5jeSJ9.8gOXrJC0X7p01oPLq22xYuquFFnrrPBOeWw3et26gL8

{
    "firstName": "Thomas",
    "lastName": "Shelby",
    "email": "shel@ms.netss",
    "password": "shelpass",
    "roleId": "203d52e2-aab5-4033-a938-f2c0a4a1198c",
    "agencyId": "2b19ea40-7f27-b3b3-be8f-a93885f0a15d"
}
