@host = http://localhost:5000

GET {{host}}/users/tourists
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ODM2ZDRjMS0yYzg5LTQ1YmYtODcyMS04MDdkY2QxNmI1MzIiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwicm9sZSI6IkN1c3RvbWVyIiwiYWdlbmN5SWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJlbWFpbCI6ImRvZUpvaG5AbXMubmV0IiwiUGVybWlzc2lvbnMiOlsiUmVhZEV4Y3Vyc2lvbnMiLCJSZWFkUGFja2FnZXMiLCJSZWFkQWdlbmNpZXMiLCJSZWFkSG90ZWxzIiwiUmVhZEhvdGVsRGVhbHMiLCJSZWFkUGFja2FnZXMiLCJXcml0ZVRvdXJpc3RzIiwiUmVhZFRvdXJpc3RzIl0sImp0aSI6Ijk1YWE3YWZlLWEzZWUtNDVkMy04ZTIwLWIwNjkxMzExOWQzMyIsImV4cCI6MTcxMzc3MzYwMSwiaXNzIjoiVHJhdmVsQWdlbmN5IiwiYXVkIjoiVHJhdmVsQWdlbmN5In0.kBJi_smmTx8lOIbPaI9RB0wzpjdriui1GaGl3TFVCOk