@host = http://localhost:5000

DELETE  {{host}}/agencies/hoteldeal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZmFjMzhiNS0zYmI0LTQyOTEtYWU3OC01NTJhM2IwMDI2N2YiLCJnaXZlbl9uYW1lIjoiVGhvbWFzIiwiZmFtaWx5X25hbWUiOiJTaGVsYnkiLCJyb2xlIjoiTWFya2V0aW5nIEFnZW50IiwiYWdlbmN5SWQiOiIyYjE5ZWE0MC03ZjI3LWIzYjMtYmU4Zi1hOTM4ODVmMGExNWQiLCJlbWFpbCI6InNoZWxAbXMubmV0c3MiLCJQZXJtaXNzaW9ucyI6WyJXcml0ZVVzZXJzIiwiV3JpdGVFeGN1cnNpb25zIiwiV3JpdGVQYWNrYWdlcyIsIldyaXRlUm9sZXMiLCJXcml0ZVRvdXJpc3RzIiwiV3JpdGVGYWNpbGl0aWVzIiwiV3JpdGVQYWNrYWdlUmVzZXJ2YXRpb24iLCJXcml0ZUFnZW5jaWVzIl0sImp0aSI6IjFhNWVmYzg1LTcwOTMtNDk3NS1hZjYxLWZjMTEyY2E4NGIzZiIsImV4cCI6MTcxMjA1MjIwOCwiaXNzIjoiVHJhdmVsQWdlbmN5IiwiYXVkIjoiVHJhdmVsQWdlbmN5In0.wRQ7tPM0LiNOeYawou1oTKOF9uE3xN6u-YiQKFAIsew

{
    "hotelDealId": "1e440188-54d3-4663-84d4-2f818b5196cc"
}