@host = http://localhost:5000

POST  {{host}}/reservation/package
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZjZjMzNjZC01MDBlLTQ5ZDgtOTc5Mi1mYmU1YTkxNDU2MGIiLCJnaXZlbl9uYW1lIjoiU2hlcmxvY2siLCJmYW1pbHlfbmFtZSI6IkhvbG1lcyIsInJvbGUiOiJTdXBlciBBZG1pbiIsImFnZW5jeUlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIiwiZW1haWwiOiJob2xtZXNAbWFpbC5uZXQiLCJQZXJtaXNzaW9ucyI6WyJXcml0ZVVzZXJzIiwiV3JpdGVFeGN1cnNpb25zIiwiV3JpdGVQYWNrYWdlcyIsIldyaXRlUm9sZXMiLCJXcml0ZVRvdXJpc3RzIiwiV3JpdGVGYWNpbGl0aWVzIiwiV3JpdGVQYWNrYWdlUmVzZXJ2YXRpb24iLCJXcml0ZUFnZW5jaWVzIiwiUmVhZEFnZW5jaWVzIiwiUmVhZEhvdGVscyIsIlJlYWRIb3RlbERlYWxzIiwiUmVhZFBhY2thZ2VzIiwiUmVhZEV4Y3Vyc2lvbnMiLCJSZWFkVXNlcnMiLCJSZWFkUm9sZXMiLCJSZWFkQWlybGluZXMiLCJSZWFkVG91cmlzdHMiLCJSZWFkRmFjaWxpdGllcyIsIlJlYWRQYWNrYWdlUmVzZXJ2YXRpb24iXSwianRpIjoiY2QzMWE5NGItN2U2NS00ZmViLThjZTAtNTMzZTk3OGNhN2I2IiwiZXhwIjoxNzEyMDQzMDA1LCJpc3MiOiJUcmF2ZWxBZ2VuY3kiLCJhdWQiOiJUcmF2ZWxBZ2VuY3kifQ.Lcpf0ReJM7RbL7ZkTccFC-xF0cAgGYbgfLDk3OWYrWo

{
  "AirlineId": "29ac892f-5dcf-41f7-b707-9a9bb292ac9b",
  "Price": 300,
  "ReservationDate": "2024-04-19T03:28:45.548Z",
  "UserId": "13bddc75-ac9f-4816-a374-1c88318509a4",
  "PackageId": "14c5c7d8-c81e-43ae-a8bd-e3c2d06d30ee",
  "TouristsGuid": [
      "c1ec4e06-0bb7-4eb5-8862-351093794aef"
  ]
}