@host = http://localhost:5000

POST  {{host}}/reservation/package
Content-Type: application/json

{
  "airline": "Air Europa",
  "price": 300,
  "reservationDate": "2024-03-19T03:28:45.548Z",
  "userId": "51041bd1-39c9-4a69-8ffb-8829b50b4c15",
  "packageId": "21e0ec24-c229-4cbf-ac15-bafd170297d9",
  "tourists": [
    {
      "id": "12345678911",
      "firstName": "Adam",
      "lastName": "Smith",
      "nationality": "Irish"
    }
  ]
}