@host = http://localhost:5000

DELETE  {{host}}/reservation/package
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZjZjMzNjZC01MDBlLTQ5ZDgtOTc5Mi1mYmU1YTkxNDU2MGIiLCJnaXZlbl9uYW1lIjoiU2hlcmxvY2siLCJmYW1pbHlfbmFtZSI6IkhvbG1lcyIsInJvbGUiOiJTdXBlciBBZG1pbiIsImFnZW5jeUlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIiwiZW1haWwiOiJob2xtZXNAbWFpbC5uZXQiLCJQZXJtaXNzaW9ucyI6WyJXcml0ZVVzZXJzIiwiV3JpdGVFeGN1cnNpb25zIiwiV3JpdGVQYWNrYWdlcyIsIldyaXRlUm9sZXMiLCJXcml0ZVRvdXJpc3RzIiwiV3JpdGVGYWNpbGl0aWVzIiwiV3JpdGVQYWNrYWdlUmVzZXJ2YXRpb24iLCJXcml0ZUFnZW5jaWVzIiwiUmVhZEFnZW5jaWVzIiwiUmVhZEhvdGVscyIsIlJlYWRIb3RlbERlYWxzIiwiUmVhZFBhY2thZ2VzIiwiUmVhZEV4Y3Vyc2lvbnMiLCJSZWFkVXNlcnMiLCJSZWFkUm9sZXMiLCJSZWFkQWlybGluZXMiLCJSZWFkVG91cmlzdHMiLCJSZWFkRmFjaWxpdGllcyIsIlJlYWRQYWNrYWdlUmVzZXJ2YXRpb24iXSwianRpIjoiNjQzMDA4MDYtOWZhNy00ZjM3LWE5MWYtZDJiYzM3MWYwYjkyIiwiZXhwIjoxNzEyMDQ5MjQxLCJpc3MiOiJUcmF2ZWxBZ2VuY3kiLCJhdWQiOiJUcmF2ZWxBZ2VuY3kifQ.1SRn5At2eoBUzsVCbsH8qLIE3d14hiR1Jrbt_wbVw0U

{
  "id": "7475fe89-a021-4abb-8b40-ed7fa02009c0"
}