@host = http://localhost:5000

GET  {{host}}/reservation/package
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4N2FjZTgzZS1lNjU3LTRjYTctYTk5ZS1hNGZmZTViNjc3YmUiLCJnaXZlbl9uYW1lIjoiU2hlcmxvY2siLCJmYW1pbHlfbmFtZSI6IkhvbG1lcyIsInJvbGUiOiJTdXBlciBBZG1pbiIsImFnZW5jeUlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIiwiZW1haWwiOiJob2xtZXNAbWFpbC5uZXQiLCJQZXJtaXNzaW9ucyI6WyJXcml0ZVVzZXJzIiwiV3JpdGVFeGN1cnNpb25zIiwiV3JpdGVQYWNrYWdlcyIsIldyaXRlUm9sZXMiLCJXcml0ZVRvdXJpc3RzIiwiV3JpdGVGYWNpbGl0aWVzIiwiV3JpdGVQYWNrYWdlUmVzZXJ2YXRpb24iLCJXcml0ZUFnZW5jaWVzIiwiUmVhZEFnZW5jaWVzIiwiUmVhZEhvdGVscyIsIlJlYWRIb3RlbERlYWxzIiwiUmVhZFBhY2thZ2VzIiwiUmVhZEV4Y3Vyc2lvbnMiLCJSZWFkVXNlcnMiLCJSZWFkUm9sZXMiLCJSZWFkQWlybGluZXMiLCJSZWFkVG91cmlzdHMiLCJSZWFkRmFjaWxpdGllcyIsIlJlYWRQYWNrYWdlUmVzZXJ2YXRpb24iXSwianRpIjoiNzA4MGJhODItZDE0MC00MjcwLWI1YWItMDlhZWY5ODU0YTQyIiwiZXhwIjoxNzEyMDIyNTMyLCJpc3MiOiJUcmF2ZWxBZ2VuY3kiLCJhdWQiOiJUcmF2ZWxBZ2VuY3kifQ.nV1D5AKVQvJKsISmLn6CBiaOoOoRz4sfO9ak0loklOc