@host = http://localhost:5000

POST  {{host}}/packages/
Content-Type: application/json

{
  "description": "string",
  "price": 0,
  "arrivalDate": "2024-03-19T03:28:45.548Z",
  "departureDate": "2024-03-19T03:28:45.548Z",
  "facilityIds": [],
  "extendedExcursionIds": []
}