@host = http://localhost:5000

GET {{host}}/Roles/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkY2EyZmI5My0zZmM0LTQ2MjEtYjAwYy0yYmQ4YzgxMDRkMDIiLCJnaXZlbl9uYW1lIjoiU2hlcmxvY2siLCJmYW1pbHlfbmFtZSI6IkhvbG1lcyIsInJvbGUiOiJTdXBlciBBZG1pbiIsImFnZW5jeUlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIiwiZW1haWwiOiJob2xtZXNAbWFpbC5uZXQiLCJQZXJtaXNzaW9ucyI6WyJXcml0ZVVzZXJzIiwiV3JpdGVFeGN1cnNpb25zIiwiV3JpdGVQYWNrYWdlcyIsIldyaXRlUm9sZXMiLCJXcml0ZVRvdXJpc3RzIiwiV3JpdGVGYWNpbGl0aWVzIiwiV3JpdGVQYWNrYWdlUmVzZXJ2YXRpb24iLCJXcml0ZUFnZW5jaWVzIiwiUmVhZEFnZW5jaWVzIiwiUmVhZEhvdGVscyIsIlJlYWRIb3RlbERlYWxzIiwiUmVhZFBhY2thZ2VzIiwiUmVhZEV4Y3Vyc2lvbnMiLCJSZWFkVXNlcnMiLCJSZWFkUm9sZXMiLCJSZWFkQWlybGluZXMiLCJSZWFkVG91cmlzdHMiLCJSZWFkRmFjaWxpdGllcyIsIlJlYWRQYWNrYWdlUmVzZXJ2YXRpb24iLCJSZWFkU3RhdGlzdGljcyJdLCJqdGkiOiI4MGJjZTI4NS05OGEwLTQyZmItYmZmMC1mMTE2MzdhZjVkYjYiLCJleHAiOjE3MTIwNTA4NDYsImlzcyI6IlRyYXZlbEFnZW5jeSIsImF1ZCI6IlRyYXZlbEFnZW5jeSJ9.FIa4OLydypiieceKPDWNbaz3VO7L8_X4UmG66rzII3s