name: .NET Core Build

on:
 workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: Execute
      run: dotnet run &
      
    - name: Start ngrok
      uses: luisboto/ngrok-tunnel-action@v0.1.7.2
      with:
         timeout: 1h
         port: 5000
         ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
         tunnel_type: http
    
    - name: Install jq
      run: sudo apt-get install jq
    - name: Get ngrok URL
      run: |
        echo "NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')" >> $GITHUB_ENV

    - name: Print ngrok URL
      run: echo "${{ env.NGROK_URL }}"

    # TODO: need to decide a default branch to tests (for example develop) in 
    # the frontend project 
    # - name: Checkout target repository
    #   uses: actions/checkout@v2
    #   with:
    #      repository: Albaros02- 
    #      token: ${{ secrets.TARGET_REPO_TOKEN }}
    # - name: Make changes
    #   run: echo "NGROK_URL=${{ env.NGROK_URL }}" > NGROK_ENV.env

    # - name: Configure Git
    #   run: |
    #      git config --global user.name "GitHubWorkFlow"
    #      git config --global user.email "name@mail.com"
         
    # - name: Commit and push changes
    #   run: |
    #      git add ./NGROK_ENV.env
    #      git commit -m "Update ngrok Url"
    #      git push 
         
    - name: Loop 
      run: |
         start=$(date +%s)
         while : ; do
           echo "Running..."
           sleep 1
           current=$(date +%s)
           elapsed=$((current - start))
           if ((elapsed > 300)); then
             break
           fi
         done
